name: untitled12
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.4.0
  image_picker: ^1.0.4
  cloud_firestore: 4.14.0
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  url_launcher: ^6.2.1
  scroll_loop_auto_scroll: ^0.0.5
  qr_flutter: ^4.1.0
  geocoding: ^2.1.1
  intl: ^0.18.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/icon1.png"
  android: true
  ios: true
  image_path_android: "android_app_icon1.png"
  image_path_ios: "ios_app_icon.png"
  adaptive_icon_background: "android_background.png"
  adaptive_icon_foreground: "android_foreground.png"
  android_resolutions: "48x48,72x72,96x96"
  ios_resolutions: "60x60,120x120,180x180"

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fnl.png
    - assets/hh copy.png
    - assets/trainMate.png
    - assets/icon1.png
    - assets/contact.jpeg
    - assets/booking.png
    - assets/upgrde.png
    - assets/qr.jpeg
    - assets/train.jpeg
    - assets/profile2.png
    - assets/profile1.jpeg
    - assets/profile3.jpeg
    -