// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9PKrPX5RRy6P8osM1U2eVFyuFkCKGrk',
    appId: '1:1041965452849:web:d8b564a38c4bc1047bcf10',
    messagingSenderId: '1041965452849',
    projectId: 'flutterauth-2fe43',
    authDomain: 'flutterauth-2fe43.firebaseapp.com',
    databaseURL: 'https://flutterauth-2fe43-default-rtdb.firebaseio.com',
    storageBucket: 'flutterauth-2fe43.appspot.com',
    measurementId: 'G-LWHE39Q4C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGBWeuhv4euiJbHQG95wDSfYb1C9s-35o',
    appId: '1:1041965452849:android:7f80a4152deb01727bcf10',
    messagingSenderId: '1041965452849',
    projectId: 'flutterauth-2fe43',
    databaseURL: 'https://flutterauth-2fe43-default-rtdb.firebaseio.com',
    storageBucket: 'flutterauth-2fe43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg7Dqf6DZlfmK3RATr2W3LjDhdkKfGcxQ',
    appId: '1:1041965452849:ios:2f1f8633ec598b5c7bcf10',
    messagingSenderId: '1041965452849',
    projectId: 'flutterauth-2fe43',
    databaseURL: 'https://flutterauth-2fe43-default-rtdb.firebaseio.com',
    storageBucket: 'flutterauth-2fe43.appspot.com',
    iosBundleId: 'com.example.untitled12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg7Dqf6DZlfmK3RATr2W3LjDhdkKfGcxQ',
    appId: '1:1041965452849:ios:9d1fc318127c6aba7bcf10',
    messagingSenderId: '1041965452849',
    projectId: 'flutterauth-2fe43',
    databaseURL: 'https://flutterauth-2fe43-default-rtdb.firebaseio.com',
    storageBucket: 'flutterauth-2fe43.appspot.com',
    iosBundleId: 'com.example.untitled12.RunnerTests',
  );
}
